### ISSUE TITLE
error when migrating

### ISSUE THREAD

**Issue by prestwich** [kcole16/near-evm-demo#1]
```
{ Error: Class PublicKey is missing in schema: publicKey
    at serializeStruct (/home/james/devel/near-web3-provider/node_modules/nearlib/lib/utils/serialize.js:245:15)
    at serializeField (/home/james/devel/near-web3-provider/node_modules/nearlib/lib/utils/serialize.js:232:13)
    at structSchema.fields.map (/home/james/devel/near-web3-provider/node_modules/nearlib/lib/utils/serialize.js:249:13)
    at Array.map (<anonymous>)
    at serializeStruct (/home/james/devel/near-web3-provider/node_modules/nearlib/lib/utils/serialize.js:248:29)
    at Object.serialize (/home/james/devel/near-web3-provider/node_modules/nearlib/lib/utils/serialize.js:271:5)
    at signTransactionObject (/home/james/devel/near-web3-provider/node_modules/nearlib/lib/transaction.js:182:33)
    at Object.signTransaction (/home/james/devel/near-web3-provider/node_modules/nearlib/lib/transaction.js:200:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  fieldPath: [ 'publicKey' ],
  originalMessage: 'Class PublicKey is missing in schema' }
```

To reproduce
1. run local near testnet
2. use branch `initial-migration-work` of this repo
2. use branch `callFunction-broken` of `summa-tx/near-web3-provider`
3. run `truffle migrate --network near` in this repo

**Comment by prestwich** [comment]
this can be fixed by adding the following lines to `nearlib/lib/transaction.js` at L182 (first line of `signTransactionObject`)
```
    exports.SCHEMA.set(transaction.publicKey.constructor, { kind: 'struct', fields: [
                ['keyType', 'u8'],
                ['data', [32]]
            ] });
```
